### PR TITLE
(CONT-702) - Implement reusable workflows

### PR DESCRIPTION
**Pull request by jordanbreen28**
This PR implements the reusable workflows for this gem.

### CODE REVIEW

**Comment by jordanbreen28** [comment]
/lib/puppet-lint/plugins/version.rb had to be moved to /lib/puppet-lint-check_unsafe_interpolations/version.rb in order to work with reusable release prep workflow.
Example of successful release prep run [here](https://github.com/puppetlabs/puppet-lint-check_unsafe_interpolations/actions/runs/4366473075) and PR [here](https://github.com/puppetlabs/puppet-lint-check_unsafe_interpolations/pull/38)

**Comment by chelnak** [comment]
I think this will break the plugin.

The linter plugins rely on folder structure to end up in the right place.

**Comment by jordanbreen28** [comment]
> I think this will break the plugin.
> 
> The linter plugins rely on folder structure to end up in the right place.

@chelnak yeah so was hoping to get some input on this one, from yourself or @GSPatton. What you're saying about folder structure is 100% correct, because initially I experimented with moving all files in `/lib/puppet-lint/plugins/` to `/lib/puppet-lint-check_unsafe_interpolations` and that definitely did break the plugin and all of the spec tests.

So I opted to move just `version.rb` to `/lib/puppet-lint-check_unsafe_interpolations` whilst leaving `check_unsafe_interpolations.rb` in the files original location. The plugin seemed to run and pass all spec tests with this, but if you think this can have a worse knock on effect I can note this to be a caveat for the gem release prep process :-)

**Comment by jordanbreen28** [comment]
Moved version.rb file back to its original location in /lib/puppet-lint/version.rb

**Review by chelnak — APPROVED** [review]

**Pull request merged**
